name: Terraform Plan

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - devops/dockerization

jobs:
  terraform:
    name: Terraform Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.HCP_TOKEN }}
      TF_VAR_hostinger_api_token: ${{ secrets.HOSTINGER_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.16.3

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan